backend:
  name: git-gateway
  branch: master

media_folder: "static/img"
public_folder: "uploads"

collections:
  - name: "books"
    label: "Books"
    folder: "content/Books"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
